/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.CrudMovimentacao;

import br.com.Classes.Movimentacao;
import br.com.Exceptions.DataSourceException;
import br.com.Exceptions.MovimentacaoException;
import br.com.Servicos.ServicoMovimentacao;
import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class TelaEditarMovimentacao extends javax.swing.JInternalFrame {

    public static Movimentacao movimentacao;
    public static int id;

    /**
     * Creates new form TelaEditarDespesa1
     */
    public TelaEditarMovimentacao() {
        initComponents();
        jTextFieldNomeDaMovimentacao.setText(movimentacao.getNomeMovimentacao());
        jFormattedTextFieldData.setText(movimentacao.getDataMovimentacao());
        jTextFieldValor.setText(movimentacao.getValorMovimentacao());

        if (movimentacao.getMovimentacaoFixa().equalsIgnoreCase("Não Fixa")) {
            jFormattedTextFieldNumeroDeParcelas.setText(movimentacao.getNumeroDeParcelas());

        } else {
            jRadioFixaEditarMovimentacao.setSelected(true);
            jFormattedTextFieldNumeroDeParcelas.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelEditarMovimentacao = new javax.swing.JPanel();
        jLabelNomeDaMovimentacao = new javax.swing.JLabel();
        jTextFieldNomeDaMovimentacao = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabelNumeroDeParcelas = new javax.swing.JLabel();
        jLabeNomelPessoa = new javax.swing.JLabel();
        jComboBoxNomePessoa = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jRadioFixaEditarMovimentacao = new javax.swing.JRadioButton();
        jFormattedTextFieldNumeroDeParcelas = new javax.swing.JFormattedTextField();
        jTextFieldValor = new javax.swing.JFormattedTextField();

        setClosable(true);

        painelEditarMovimentacao.setBackground(new java.awt.Color(153, 153, 153));
        painelEditarMovimentacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Movimentação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabelNomeDaMovimentacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeDaMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeDaMovimentacao.setText("Nome Movimentação");

        jTextFieldNomeDaMovimentacao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldNomeDaMovimentacaoPropertyChange(evt);
            }
        });

        jLabelValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor");

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");

        try {
            jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataActionPerformed(evt);
            }
        });

        jLabelNumeroDeParcelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumeroDeParcelas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroDeParcelas.setText("Número de Parcelas");

        jLabeNomelPessoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeNomelPessoa.setForeground(new java.awt.Color(255, 255, 255));
        jLabeNomelPessoa.setText("Movimentação de:");

        jComboBoxNomePessoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxNomePessoa.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxNomePessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contas", "Casa", "Carro", "Lazer" }));
        jComboBoxNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomePessoaActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jRadioFixaEditarMovimentacao.setBackground(new java.awt.Color(153, 153, 153));
        jRadioFixaEditarMovimentacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioFixaEditarMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        jRadioFixaEditarMovimentacao.setText("Fixa");
        jRadioFixaEditarMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFixaEditarMovimentacaoActionPerformed(evt);
            }
        });

        jFormattedTextFieldNumeroDeParcelas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout painelEditarMovimentacaoLayout = new javax.swing.GroupLayout(painelEditarMovimentacao);
        painelEditarMovimentacao.setLayout(painelEditarMovimentacaoLayout);
        painelEditarMovimentacaoLayout.setHorizontalGroup(
            painelEditarMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEditarMovimentacaoLayout.createSequentialGroup()
                .addGroup(painelEditarMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEditarMovimentacaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEditarMovimentacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelEditarMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeDaMovimentacao)
                            .addComponent(jLabelData)
                            .addComponent(jLabelNumeroDeParcelas)
                            .addGroup(painelEditarMovimentacaoLayout.createSequentialGroup()
                                .addComponent(jLabeNomelPessoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNomeDaMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValor)
                            .addGroup(painelEditarMovimentacaoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jFormattedTextFieldNumeroDeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioFixaEditarMovimentacao))
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelEditarMovimentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelEditarMovimentacaoLayout.setVerticalGroup(
            painelEditarMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEditarMovimentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeDaMovimentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeDaMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEditarMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeNomelPessoa)
                    .addComponent(jComboBoxNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNumeroDeParcelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEditarMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioFixaEditarMovimentacao)
                    .addComponent(jFormattedTextFieldNumeroDeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(painelEditarMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelEditarMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelEditarMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomePessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNomePessoaActionPerformed

    private void jTextFieldNomeDaMovimentacaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldNomeDaMovimentacaoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeDaMovimentacaoPropertyChange

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        int dialogResult = JOptionPane.showInternalConfirmDialog(this, "Deseja realmente alterar?");
        if (dialogResult == 0) {

            int erro = 0;

            movimentacao.setNomeMovimentacao(jTextFieldNomeDaMovimentacao.getText());
            movimentacao.setProprietarioDaMovimentacao(jComboBoxNomePessoa.getSelectedItem().toString());
            movimentacao.setValorMovimentacao(jTextFieldValor.getText().replace(',', '.'));
            movimentacao.setDataMovimentacao(jFormattedTextFieldData.getText());

            ServicoMovimentacao servicoMovimentacao = new ServicoMovimentacao();
            boolean nomeMovimentacao = servicoMovimentacao.verificarNomeMovementacao(movimentacao.getNomeMovimentacao());
            boolean valorMovimentacao = servicoMovimentacao.verificarValorMovimentacao(movimentacao.getValorMovimentacao());
            boolean dataMovimentacao = servicoMovimentacao.verificarDataMovimentacao(movimentacao.getDataMovimentacao());
            boolean numeroDeParcelas = servicoMovimentacao.verificarNumeroDeParcelas(movimentacao.getNumeroDeParcelas());

            if (nomeMovimentacao == false) {
                jTextFieldNomeDaMovimentacao.setBackground(Color.PINK);
                erro++;
            } else {
                jTextFieldNomeDaMovimentacao.setBackground(Color.WHITE);
            }
            if (valorMovimentacao == false) {
                jTextFieldValor.setBackground(Color.PINK);
                erro++;
            } else {
                jTextFieldValor.setBackground(Color.WHITE);
            }
            if (dataMovimentacao == false) {
                jFormattedTextFieldData.setBackground(Color.PINK);
                erro++;
            } else {
                jFormattedTextFieldData.setBackground(Color.WHITE);
            }
            if (numeroDeParcelas == false && !jRadioFixaEditarMovimentacao.isSelected()) {
                jFormattedTextFieldNumeroDeParcelas.setBackground(Color.PINK);
                erro++;
            } else {
                jFormattedTextFieldNumeroDeParcelas.setBackground(Color.WHITE);
            }
            if (erro == 0) {
                try {
                    servicoMovimentacao.editarMovimentacao(id, movimentacao);
                    JOptionPane.showMessageDialog(this, "Movimentação alterada com sucesso!");
                    this.dispose();
                } catch (DataSourceException ex) {
                    Logger.getLogger(TelaEditarMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (dialogResult == 2) {
            this.dispose();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jFormattedTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int dialogResult = JOptionPane.showInternalConfirmDialog(this, "Deseja realmente cancelar?");
        if (dialogResult == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jRadioFixaEditarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFixaEditarMovimentacaoActionPerformed
        if (jRadioFixaEditarMovimentacao.isSelected()) {
            jFormattedTextFieldNumeroDeParcelas.setEnabled(false);
        } else {
            jFormattedTextFieldNumeroDeParcelas.setBackground(Color.WHITE);
            jFormattedTextFieldNumeroDeParcelas.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioFixaEditarMovimentacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    public javax.swing.JComboBox<String> jComboBoxNomePessoa;
    public javax.swing.JFormattedTextField jFormattedTextFieldData;
    public javax.swing.JFormattedTextField jFormattedTextFieldNumeroDeParcelas;
    private javax.swing.JLabel jLabeNomelPessoa;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelNomeDaMovimentacao;
    private javax.swing.JLabel jLabelNumeroDeParcelas;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JRadioButton jRadioFixaEditarMovimentacao;
    public javax.swing.JTextField jTextFieldNomeDaMovimentacao;
    private javax.swing.JFormattedTextField jTextFieldValor;
    private javax.swing.JPanel painelEditarMovimentacao;
    // End of variables declaration//GEN-END:variables

    
}
