/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.CrudMovimentacao;

import br.com.Classes.Movimentacao;
import br.com.Exceptions.DataSourceException;
import br.com.Servicos.ServicoMovimentacao;
import java.awt.Color;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.util.logging.Logger;


/**
 *
 * @author jonat
 */
public class TelaNovaMovimentacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaNovaDespesa1
     */
    public TelaNovaMovimentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoMovimentacao = new javax.swing.ButtonGroup();
        painelNovaDespesa = new javax.swing.JPanel();
        labelNomeDaMovimentacao = new javax.swing.JLabel();
        textFieldNomeDaMovimentacao = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        formattedTextFieldData = new javax.swing.JFormattedTextField();
        labelNumeroDeParcelas = new javax.swing.JLabel();
        jLabelNomePessoa = new javax.swing.JLabel();
        jComboBoxNomePessoa = new javax.swing.JComboBox<>();
        botaoCancelar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        radioFixaNovaMovimentacao = new javax.swing.JRadioButton();
        jLabelStatus = new javax.swing.JLabel();
        jRadioButtonStatusPago = new javax.swing.JRadioButton();
        jFormattedTextFieldNumeroDeParcelas = new javax.swing.JFormattedTextField();
        jRadioButtonDespesa = new javax.swing.JRadioButton();
        jRadioButtonReceita = new javax.swing.JRadioButton();
        textFieldValor = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setVisible(true);

        painelNovaDespesa.setBackground(new java.awt.Color(153, 153, 153));
        painelNovaDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nova Movimentação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        labelNomeDaMovimentacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNomeDaMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeDaMovimentacao.setText("Nome da Despesa");

        labelValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelValor.setForeground(new java.awt.Color(255, 255, 255));
        labelValor.setText("Valor");

        labelData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelData.setForeground(new java.awt.Color(255, 255, 255));
        labelData.setText("Vencimento");

        try {
            formattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelNumeroDeParcelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNumeroDeParcelas.setForeground(new java.awt.Color(255, 255, 255));
        labelNumeroDeParcelas.setText("Número de Parcelas");

        jLabelNomePessoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomePessoa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomePessoa.setText("Despesa de:");

        jComboBoxNomePessoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxNomePessoa.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxNomePessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contas", "Casa", "Carro", "Lazer" }));
        jComboBoxNomePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomePessoaActionPerformed(evt);
            }
        });

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(102, 102, 102));
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(102, 102, 102));
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        radioFixaNovaMovimentacao.setBackground(new java.awt.Color(153, 153, 153));
        radioFixaNovaMovimentacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioFixaNovaMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        radioFixaNovaMovimentacao.setText("Fixa");
        radioFixaNovaMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFixaNovaMovimentacaoActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Status");

        jRadioButtonStatusPago.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButtonStatusPago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonStatusPago.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonStatusPago.setText("Pago");

        jFormattedTextFieldNumeroDeParcelas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jRadioButtonDespesa.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupTipoMovimentacao.add(jRadioButtonDespesa);
        jRadioButtonDespesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonDespesa.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDespesa.setSelected(true);
        jRadioButtonDespesa.setText("Despesa");
        jRadioButtonDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDespesaActionPerformed(evt);
            }
        });

        jRadioButtonReceita.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupTipoMovimentacao.add(jRadioButtonReceita);
        jRadioButtonReceita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonReceita.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonReceita.setText("Receita");
        jRadioButtonReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReceitaActionPerformed(evt);
            }
        });

        textFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout painelNovaDespesaLayout = new javax.swing.GroupLayout(painelNovaDespesa);
        painelNovaDespesa.setLayout(painelNovaDespesaLayout);
        painelNovaDespesaLayout.setHorizontalGroup(
            painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNovaDespesaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCancelar)
                .addGap(6, 6, 6))
            .addGroup(painelNovaDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelNovaDespesaLayout.createSequentialGroup()
                        .addComponent(jRadioButtonDespesa)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonReceita))
                    .addComponent(labelNomeDaMovimentacao)
                    .addComponent(labelValor)
                    .addComponent(textFieldNomeDaMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelNovaDespesaLayout.createSequentialGroup()
                        .addComponent(jLabelNomePessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroDeParcelas)
                    .addComponent(jLabelStatus)
                    .addComponent(jRadioButtonStatusPago)
                    .addGroup(painelNovaDespesaLayout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldNumeroDeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioFixaNovaMovimentacao))
                    .addGroup(painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textFieldValor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelNovaDespesaLayout.setVerticalGroup(
            painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNovaDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDespesa)
                    .addComponent(jRadioButtonReceita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNomeDaMovimentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomeDaMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomePessoa)
                    .addComponent(jComboBoxNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNumeroDeParcelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNumeroDeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioFixaNovaMovimentacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonStatusPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(painelNovaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelNovaDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelNovaDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jComboBoxNomePessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomePessoaActionPerformed

    }//GEN-LAST:event_jComboBoxNomePessoaActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        int erro = 0;
        
        Movimentacao movimentacao = new Movimentacao();
        
        if (jRadioButtonDespesa.isSelected()){
            movimentacao.setTipoMovimentacao("Despesa");
        } else {
            movimentacao.setTipoMovimentacao("Receita");
        }
        
        if (radioFixaNovaMovimentacao.isSelected()){
            movimentacao.setMovimentacaoFixa("Fixa");
        } else {
            movimentacao.setMovimentacaoFixa("Não Fixa");
        }
        
        
        if (jRadioButtonReceita.isSelected()) {
            movimentacao.setStatusDespesa(" ");
        }
        if (jRadioButtonDespesa.isSelected() && jRadioButtonStatusPago.isSelected()) {
            movimentacao.setStatusDespesa("Pago");
        }
        if (jRadioButtonDespesa.isSelected() && !jRadioButtonStatusPago.isSelected()) {
            movimentacao.setStatusDespesa("Não Pago");
        }
        if (radioFixaNovaMovimentacao.isSelected()) {
            movimentacao.setNumeroDeParcelas("999999999");
        } else {
            movimentacao.setNumeroDeParcelas(jFormattedTextFieldNumeroDeParcelas.getText());
        }
        
        movimentacao.setMovimentacaoEnabled("true");

        movimentacao.setNomeMovimentacao(textFieldNomeDaMovimentacao.getText());
        movimentacao.setProprietarioDaMovimentacao(jComboBoxNomePessoa.getSelectedItem().toString());
        movimentacao.setDataMovimentacao(formattedTextFieldData.getText());
        movimentacao.setValorMovimentacao(textFieldValor.getText().replace(',', '.'));

        ServicoMovimentacao servicoMovimentacao = new ServicoMovimentacao();
        boolean nomeDaMovimentacao = servicoMovimentacao.verificarNomeMovementacao(movimentacao.getNomeMovimentacao());
        boolean dataMovimentacao = servicoMovimentacao.verificarDataMovimentacao(movimentacao.getDataMovimentacao());
        boolean numeroDeParcelas = servicoMovimentacao.verificarNumeroDeParcelas(movimentacao.getNumeroDeParcelas());
        boolean valorMovimentacao = servicoMovimentacao.verificarValorMovimentacao(movimentacao.getValorMovimentacao());

        if (nomeDaMovimentacao == false) {
            textFieldNomeDaMovimentacao.setBackground(Color.PINK);
            erro++;
        } else {
            textFieldNomeDaMovimentacao.setBackground(Color.WHITE);
        }
        if (dataMovimentacao == false) {
            formattedTextFieldData.setBackground(Color.PINK);
            erro++;
        } else {
            formattedTextFieldData.setBackground(Color.WHITE);
        }
        if (valorMovimentacao == false) {
            textFieldValor.setBackground(Color.PINK);
            erro++;
        } else {
            textFieldValor.setBackground(Color.WHITE);
        }
        if (numeroDeParcelas == false && !radioFixaNovaMovimentacao.isSelected()) {
            jFormattedTextFieldNumeroDeParcelas.setBackground(Color.PINK);
            erro++;
        } else {
            jFormattedTextFieldNumeroDeParcelas.setBackground(Color.WHITE);
        }

        if (erro == 0 && jRadioButtonDespesa.isSelected()) {
            JOptionPane.showMessageDialog(this, "Despesa Cadastrada!");
            this.dispose();
        }
        if (erro == 0 && jRadioButtonReceita.isSelected()) {
            JOptionPane.showMessageDialog(this, "Receita Cadastrada!");
            this.dispose();
        }
        if (erro == 0 && !radioFixaNovaMovimentacao.isSelected()){
            try {
                servicoMovimentacao.parcelarMovimentacao(movimentacao);
            } catch (DataSourceException ex) {
                Logger.getLogger(TelaNovaMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(TelaNovaMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (erro == 0 && radioFixaNovaMovimentacao.isSelected()){
            try {
                servicoMovimentacao.movimentacaoFixa(movimentacao);
            } catch (Exception ex) {
                Logger.getLogger(TelaNovaMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        int dialogResult = JOptionPane.showInternalConfirmDialog(this, "Deseja realmente cancelar?");
        if (dialogResult == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void radioFixaNovaMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFixaNovaMovimentacaoActionPerformed
        if (radioFixaNovaMovimentacao.isSelected()) {
            jFormattedTextFieldNumeroDeParcelas.setEnabled(false);
        } else {
            jFormattedTextFieldNumeroDeParcelas.setBackground(Color.WHITE);
            jFormattedTextFieldNumeroDeParcelas.setEnabled(true);
        }
    }//GEN-LAST:event_radioFixaNovaMovimentacaoActionPerformed

    private void jRadioButtonDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDespesaActionPerformed
        if (jRadioButtonDespesa.isSelected()) {
            labelNomeDaMovimentacao.setText("Nome da Despesa");
            labelData.setText("Vencimento");
            jLabelStatus.setVisible(true);
            jRadioButtonStatusPago.setVisible(true);
            jLabelNomePessoa.setText("Despesa de:");
            jComboBoxNomePessoa.removeAllItems();
            jComboBoxNomePessoa.addItem("Jonata");
            jComboBoxNomePessoa.addItem("Casa");
            jComboBoxNomePessoa.addItem("Carro");
            jComboBoxNomePessoa.addItem("Lazer");

        }
    }//GEN-LAST:event_jRadioButtonDespesaActionPerformed

    private void jRadioButtonReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReceitaActionPerformed
        if (jRadioButtonReceita.isSelected()) {
            labelNomeDaMovimentacao.setText("Nome da Receita");
            labelData.setText("Recebimento");
            jLabelStatus.setVisible(false);
            jRadioButtonStatusPago.setVisible(false);
            jLabelNomePessoa.setText("Receita de:");
            jComboBoxNomePessoa.removeAllItems();
            jComboBoxNomePessoa.addItem("Jonata");

        }
    }//GEN-LAST:event_jRadioButtonReceitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.ButtonGroup buttonGroupTipoMovimentacao;
    private javax.swing.JFormattedTextField formattedTextFieldData;
    private javax.swing.JComboBox<String> jComboBoxNomePessoa;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumeroDeParcelas;
    private javax.swing.JLabel jLabelNomePessoa;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JRadioButton jRadioButtonDespesa;
    private javax.swing.JRadioButton jRadioButtonReceita;
    private javax.swing.JRadioButton jRadioButtonStatusPago;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelNomeDaMovimentacao;
    private javax.swing.JLabel labelNumeroDeParcelas;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel painelNovaDespesa;
    private javax.swing.JRadioButton radioFixaNovaMovimentacao;
    private javax.swing.JTextField textFieldNomeDaMovimentacao;
    private javax.swing.JFormattedTextField textFieldValor;
    // End of variables declaration//GEN-END:variables
}
